application: pwilliams-movie-quotes
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Serving static files
- url: /static
  static_dir: static

# Endpoints handler
- url: /_ah/spi/.*
  script: movie_quotes_api.app

- url: .*  #Always goes last
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
